### ISSUE TITLE
Randomize background

### ISSUE THREAD

**Issue by Readf0x** [catppuccin/sddm#18]
Add an option to grab a random wallpaper from a folder (please).
You could add a boolean option along the lines of `RandomBackground` that makes it grab a random image from the path specified in `Background` (the specified path would have to lead to a folder).

**Comment by isabelroses** [comment]
I don't believe this is possible due SDDM themselves. However, you can see https://github.com/sddm/sddm/issues/801#issuecomment-1722438128 which is how someone when't about solving the issue
