### ISSUE TITLE
Reboot and other buttons not working

### ISSUE THREAD

**Issue by AsarNaufil** [catppuccin/sddm#20]
Hi, the reboot and other buttons in theme do not work for me, i.e. there is no response from them after clicking.. I am not sure how to debug, so I need some help..

System:
Arch Linux x86_64
HP Notebook
Intel i3-6100U (4) @ 2.300GHz
Intel Skylake GT2 [HD Graphics]
Linux 6.6.13-1-lts
Hyprland

![image](https://github.com/catppuccin/sddm/assets/145439464/2726cbf7-cc04-45a9-ae74-967919f9822c)

Log:
```
sddm-greeter --test-mode --theme /usr/share/sddm/themes/catppuccin-macchiato/
High-DPI autoscaling Enabled
Reading from "/usr/local/share/wayland-sessions/hyprland.desktop"
Reading from "/usr/share/wayland-sessions/hyprland.desktop"
Parsing xkb rules from "/usr/share/X11/xkb/rules/evdev.xml"
Loading theme configuration from "/usr/share/sddm/themes/catppuccin-macchiato//theme.conf"
Socket error:  "QLocalSocket::connectToServer: Invalid name"
Loading file:///usr/share/sddm/themes/catppuccin-macchiato//Main.qml...
file:///usr/share/sddm/themes/catppuccin-macchiato//Main.qml:18:3: QML Image: Cannot open: file:///usr/share/sddm/themes/catppuccin-macchiato//backgrounds/wall.jpg
Adding view for "eDP-1" QRect(0,0 1366x768)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QIODevice::write (QLocalSocket): device not open
QIODevice::write (QLocalSocket): device not open
QIODevice::write (QLocalSocket): device not open
```
I am a novice, so thank you for your time and patience.

**Comment by isabelroses** [comment]
It looks like your using the command `sddm-greeter --test-mode --theme /usr/share/sddm/themes/catppuccin-macchiato/` (first line of log) to test the sddm login manager, this command is intended to test the greeter, therefore it does not contain the ablity to shut down.

**Comment by AsarNaufil** [comment]
It doesn't work in a normal login either, just showed it for important log info

**Comment by isabelroses** [comment]
Then I would assume that it would be caused by the fact your running SDDM under Wayland, inferred from this line `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`. Since SDDM is in an experimental stage with Wayland, this is likely the cause.

**Comment by AsarNaufil** [comment]
I see.. thanks.
