### ISSUE TITLE
Create ci to update OpenDesktop/Pling files.

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/sddm#23]
We should upload the SDDM theme to OpenDesktop/Pling.

I know that KDE 6 has been released and we are unsure if the current theme works so we should upload just for KDE 5 at the moment.

Personally, I'm unsure what part of this repository needs zipped up so I'd appreciate if you could provide me with it and I can upload it on Catppuccin's account @isabelroses

**Comment by isabelroses** [comment]
In theory, should only need to zip the folders within the src directory, see https://discord.com/channels/907385605422448742/1101151813836734564/1214677439440228464 for the ones I just did.

**Comment by sgoudham** [comment]
![image](https://github.com/catppuccin/sddm/assets/58985301/f620ce54-186f-4c6c-b701-bb578358115d)

Uploaded all the SDDM themes, thanks @isabelroses!

**Comment by EmKaCe** [comment]
Sorry for "reopening" this issue but the current files don't seem to work.
The zip files contain the correct contents however they require another folder above them.

Example (current state):
```
├── assets
│  └── angle-down.png
├── backgrounds
├── Components
│  ├── Clock.qml
│  ├── LoginPanel.qml
│  ├── PasswordField.qml
│  ├── PowerButton.qml
│  ├── RebootButton.qml
│  ├── SessionPanel.qml
│  ├── SleepButton.qml
│  └── UserField.qml
├── icons
│  ├── power.svg
│  ├── reboot.svg
│  ├── settings.svg
│  └── sleep.svg
├── Main.qml
├── metadata.desktop
├── preview.png
└── theme.conf
```

Should be:
```
├── mocha
│  ├── assets
│  │  └── angle-down.png
│  ├── backgrounds
│  ├── Components
│  │  ├── Clock.qml
│  │  ├── LoginPanel.qml
│  │  ├── PasswordField.qml
│  │  ├── PowerButton.qml
│  │  ├── RebootButton.qml
│  │  ├── SessionPanel.qml
│  │  ├── SleepButton.qml
│  │  └── UserField.qml
│  ├── icons
│  │  ├── power.svg
│  │  ├── reboot.svg
│  │  ├── settings.svg
│  │  └── sleep.svg
│  ├── Main.qml
│  ├── metadata.desktop
│  ├── preview.png
│  └── theme.conf
```

**Comment by isabelroses** [comment]
> Sorry for "reopening" this issue but the current files don't seem to work. The zip files contain the correct contents however they require another folder above them.

Thats fine, we needed to update the files for qt6 support anyways.

**Comment by sgoudham** [comment]
Let's repurpose this issue into creating a github actions file to generate these zips on pushes to the main branch? @isabelroses

**Comment by isabelroses** [comment]
That works for me
