### ISSUE TITLE
seems to be incompatible with plasma 6, black screen on boot

### ISSUE THREAD

**Issue by adpkjapkbpkadnbpandb** [catppuccin/sddm#24]
changing sddm theme to breeze solved it

**Comment by pluiedev** [comment]
Most likely because it needs to be ported to be compatible with Plasma 6. See here: https://develop.kde.org/docs/plasma/theme/theme-porting-to-plasma6/#changes-for-sddm-login-themes

**Comment by isabelroses** [comment]
Currently looking into the changes that need to be made. Hopefully i can get this out within the next 2 weeks.
