### ISSUE TITLE
Can't install it in nixos unless changing the metadata to qt5

### ISSUE THREAD

**Issue by iuribrindeiro** [catppuccin/sddm#30]
The theme doesn't seem to work if the `metadata.desktop` holds the `QtVersion=6`, as added in [this PR](https://github.com/catppuccin/sddm/pull/26).

After manually changing it to `QtVersion=5` it just works. 
I'm not really sure why is this, but I wanted to leave this here in case someone else has the same issue.

My solution:

```nix
{ pkgs }:

pkgs.stdenv.mkDerivation {
  name = "catppuccin-macchiato";
  src = pkgs.fetchurl {
    url = "https://github.com/catppuccin/sddm/releases/download/v1.0.0/catppuccin-macchiato.zip";
    sha256 = "1yh4f9xdm81bp8qy2yl5nw35haicfczks958zqr5c68kzr6h6hsa";
  };

  dontUnpack = true;

  installPhase = ''
    mkdir -p $out
    mkdir ./temp
    ${pkgs.unzip}/bin/unzip $src -d ./temp
    cp -R ./temp/catppuccin-macchiato/* $out/
    rm $out/metadata.desktop
    echo "
[SddmGreeterTheme]
Name=Catppuccin macchiato
Description=Soothing pastel theme for SDDM
Type=sddm-theme
Version=2.1
Website=https://github.com/catppuccin/sddm
Screenshot=preview.png
MainScript=Main.qml
ConfigFile=theme.conf
TranslationsDirectory=translations
Theme-Id=Catppuccin
Theme-API=2.0
License=MIT
QtVersion=5" > $out/metadata.desktop
  '';

}
```

**Comment by isabelroses** [comment]
Might be worth looking at https://github.com/NixOS/nixpkgs/pull/296682

**Comment by isabelroses** [comment]
Since the upstream package has been merged, I assume it has been fixed. Please do let me know if it works.

**Comment by ecarlson94** [comment]
This doesn't work for me either. In fact, this only works for NixOS users that use Qt (which I don't). I had to remove this line to get the theme to work. This tells me that we should remove this line from here and manage Qt support within the install phase of the [catppuccin-sddm package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ca/catppuccin-sddm/package.nix) instead.

**Comment by isabelroses** [comment]
Just to reiterate my point from https://github.com/catppuccin/nix/pull/168#issuecomment-2111754109, such that everyone here can see it.

> This seems like an issue you should take up with the upstream packager (nixpkgs). Since sddm is under the KDE banner so it makes sense for the catppuccin-sddm theme (and its maintainer, me) to ship it with the qt-platform set to 6 by default.
