### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by ksz16** [catppuccin/sddm#32]
In Debian 12 (qt5) date format is "Monday, 05 May 2024"
In Arch Linux and Fedora 40 (both qt6) format is "05/20/24"
Is there any way to display the date in long format (as in qt5)?

**Comment by isabelroses** [comment]
Seems to be a change in the library, should be fixable with some changes.

**Comment by isabelroses** [comment]
Also just notice, threes two dates. I assume your referring to the lower one 
![image](https://github.com/catppuccin/sddm/assets/71222764/17f49ad5-edc0-4550-9f96-2c8c41a444f6)
