### ISSUE TITLE
Custom clock format.

### ISSUE THREAD

**Issue by zhexyez** [catppuccin/sddm#35]
After not finding any concise documentation on sddm itself, I would like to ask here: is it possible to remove date from Clock component? Or remove time and let date be? Thanks.

**Comment by isabelroses** [comment]
try `ClockEnabled` in the `theme.conf` file, all options are marked here https://github.com/catppuccin/sddm?tab=readme-ov-file#configuration

**Comment by zhexyez** [comment]
> try `ClockEnabled` in the `theme.conf` file, all options are marked here https://github.com/catppuccin/sddm?tab=readme-ov-file#configuration

Thanks, but this is not enough to properly customize every inch. I've managed to understand that in order to properly customize sddm, I need to refer to Qt. For now, I've customized it, heavily diverging from original catppuccin theme, but nevertheless reused the colors, as they are awesome.
