### ISSUE TITLE
Can't use theme on arch linux.

### ISSUE THREAD

**Issue by F4LC0N69** [catppuccin/sddm#40]
Theme doesn't load at all. It shows following error message:-
```
The current theme cannot be loaded due to the errors below. Please select another theme

file:///usr/share/sddm/themes/catppuccin/Main.qml:3:1: plugin cannot be loaded for module "QtQuick.Controls":Cannot protect module QtQuick.Controls 2 as it was never registered
```

**Comment by sgoudham** [comment]
Hey there, just to confirm, do you have the following dependencies listed in the [README](https://github.com/catppuccin/sddm#arch-based-os)?

**Comment by F4LC0N69** [comment]
Yes, I have dependencies installed. I'm on Arch Hyprland.
`pacman -Syu qt6-svg qt6-declarative`

gives output:

```
warning: qt6-svg-6.7.2-1 is up to date -- reinstalling
warning: qt6-declarative-6.7.2-1 is up to date -- reinstalling
```

**Comment by Lichthagel** [comment]
If you don't mind, can you try if it works when you install plasma?

**Comment by jasonzondor** [comment]
I was getting the same error and I'm running Fedora 39 Sway Spin.  Installed plasma (dnf install @kde-desktop) and it's working.  Not sure what the other dependency I was missing.

**Comment by greed-d** [comment]
@F4LC0N69 can you try installing `qt5-quickcontrols2`

I was also encountering the same issue but installing above package fixed it
