### ISSUE TITLE
Theme Starts with on-screen keyboard by default

### ISSUE THREAD

**Issue by nekolifestyle** [catppuccin/sddm#6]
I was able to fix this by making a configuration file in /etc/sddm.conf and adding this to the first line. Tested with the latest KDE Plasma 5.27.2
```
# Input method module
InputMethod=
```

**Comment by isabelincorp** [comment]
Thanks for opening the issue! Sadly I wasn't able to replicate this, so this is going to be closed, also I think this could be an issue more with sddm rather than the theme.

**Comment by nmabhinandan** [comment]
I'm facing the same problem on KDE Neon (Ubuntu jammy), Plasma version 6.1.3
