### ISSUE TITLE
[Suggestion] Make "Red Hat-Based" to "Fedora-Based" or "RPM-Based"

### ISSUE THREAD

**Issue by xelser** [catppuccin/sddm#8]
Isn't it that Red Hat is based on Fedora and if we going to use Debian instead of Ubuntu, doesn't it make sense to use Fedora instead?

**Comment by isabelroses** [comment]
Fedora is owned by red hat, so no this change does not make sense,

**Comment by xelser** [comment]
> Fedora is owned by red hat

True but red hat enterprise linux (the distro, not the company) **IS** based on fedora. Unless we have a different definition of "based".

**Comment by isabelroses** [comment]
> I know this is just a minor nitpick, but somewhat it sticks out as the odd one compared to arch and debian.

Fair enough i guess it should be changed to RPM or something similar then.
